# Generated by Django 6.0.1 on 2026-01-11 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="position",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="tasktype",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="worker",
            options={"ordering": ["username"]},
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="hub.task",
                    ),
                ),
            ],
        ),
    ]
